---
global_settings:
  switch_control:
    ethernet_switching_mode: end-host
    fc_switching_mode: end-host
    mac_aging_option: default
    vlan_port_optimization_enabled: false
    reserved_vlan_start_id: 3915
    message_interval: 15
  network_control:
    udld: alert
  system_qos:
    classes:
      - name: Bronze
        admin_state: Enabled
        weight: 7
      - name: Silver
        admin_state: Enabled
        weight: 8
      - name: Gold
        admin_state: Enabled
        weight: 9
      - name: Platinum
        admin_state: Enabled
        weight: 10
      - name: Best Effort
        weight: 5
      - name: FC
        weight: 5
  ntp:
    enable: true
    servers:
      - time.google.com
      - pool.ntp.org
  dns:
    enable_dynamic_dns: false
    enable_ipv4_dns_from_dhcp: false
    preferred_ipv4_dns_server: 1.1.1.1
    alternate_ipv4_dns_server: 8.8.8.8
    enable_ipv6: false
    enable_ipv6_dns_from_dhcp: false
